apiVersion: v1
kind: Service
metadata:
  name: model-service
  namespace: autoops
  labels:
    app: model-service
    app.kubernetes.io/name: model-service
    app.kubernetes.io/part-of: autoops
spec:
  selector:
    app: model-service
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: model-service-ingress
  namespace: autoops
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: model-service.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: model-service
            port:
              number: 8000
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: model-service-monitor
  namespace: autoops
  labels:
    app: model-service
spec:
  selector:
    matchLabels:
      app: model-service
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
