apiVersion: v1
kind: Namespace
metadata:
  name: autoops
  labels:
    name: autoops
    app.kubernetes.io/name: autoops
    app.kubernetes.io/part-of: autoops
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: autoops-quota
  namespace: autoops
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "10"
    services: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: autoops-limits
  namespace: autoops
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
